"""
Dataset construction utilities for MassLinker.

This module defines the `ExcelDataset` class and helper functions used to load
MassLinker-tokenized Excel outputs, assemble them into PyTorch-compatible
datasets, split datasets for cross-validation, reshape MassLinker token tensors
for conventional machine-learning models, and concatenate multiple processed
datasets.

MassLinker converts raw LC-MS signals into fixed-length metabolic tokens. Each
compound-associated m/z window is represented by RBF-derived parameters,
including peak height, peak position, and peak width. The resulting tensor
structure is used by downstream differential analysis and supervised predictive
modeling.
"""

import os
import joblib
import pandas as pd
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from tqdm import tqdm
import random
import utils
import numpy as np


class ExcelDataset(Dataset):
    '''
        Used for constructing the datasets
        data_path should contain all xlsx files converted from MassLinker
        target_path should be a xlsx file contain filename、label and is_positive(1 or 0)
    '''
    """
    PyTorch Dataset wrapper for MassLinker-tokenized Excel outputs.

    Each sample is expected to be stored as a folder under `data_path`, where
    the folder contains an Excel file generated by MassLinker tokenization.
    The corresponding metadata and labels are read from `target_path`.

    The target Excel file should contain at least three columns:
    `filename`, `label`, and `is_positive`.

    Parameters
    ----------
    data_path : str
        Directory containing MassLinker-tokenized sample folders.
    target_path : str, optional
        Path to the sample annotation file. The default is `target.xlsx`.
    mode : str, optional
        Loading mode. `origin` uses the folder name directly, while `enhance`
        removes the augmentation prefix from augmented sample names.
    """

    def __init__(self, data_path, target_path="target.xlsx", mode='origin'):
        """
        Initialize the dataset by loading MassLinker token tensors and labels.
        """
        self.data_path = data_path
        self.target_path = target_path
        self.samples, self.label, self.name, self.is_positive = self.load_data(data_path, target_path, mode=mode)

    def load_data(self,
                  data_path: str,
                  target_path: str,
                  mode='origin'
                  ):
        """
        Load MassLinker-tokenized Excel files and assemble sample tensors.

        For each sample, all non-empty sheets in the corresponding Excel file
        are read and converted into tensors. The sheet data are reorganized into
        MassLinker token format, where each compound-associated m/z window is
        represented by three groups of RBF parameters.

        Parameters
        ----------
        data_path : str
            Directory containing sample folders generated by MassLinker.
        target_path : str
            Path to the target Excel file containing sample metadata and labels.
        mode : str, optional
            Loading mode. `origin` matches sample names directly. `enhance`
            removes the augmentation prefix before matching with the metadata.

        Returns
        -------
        tuple
            A tuple containing:
            samples : torch.Tensor
                Tensor of MassLinker metabolic tokens.
            labels : list
                Sample labels from the metadata file.
            name : list
                Sample names matched to the metadata file.
            is_positives : torch.Tensor
                Binary group labels used for two-group analysis.
        """
        ret = []
        target_df = pd.read_excel(target_path)
        labels = []
        name = []
        is_positives = []

        for filename in tqdm(os.listdir(data_path)):
            # In enhanced mode, remove the augmentation prefix before matching
            # the sample name to the target metadata table.
            if mode == "enhance":
                split = filename.split('-')
                add_name = ""
                for i in range(1, len(split)):
                    add_name += split[i]
                    add_name += "-"
                add_name = add_name[:-1]
            else:
                add_name = filename

            ret.append([])

            # Each tokenized sample must have a matching record in target.xlsx.
            if add_name not in target_df.iloc[:, 0].tolist():
                raise Exception(f"{add_name} not in target xlsx")

            condition = target_df['filename'] == add_name
            label = target_df["label"][condition]
            is_positive = torch.tensor(target_df["is_positive"][condition].item())

            is_positives.append(is_positive)
            labels.append(label)
            name.append(add_name)

            # Expected MassLinker tokenizer output:
            # data_path / sample_name / sample_name.xlsx
            f_name = os.path.join(data_path, filename, filename + ".xlsx")
            sheets = pd.read_excel(f_name, sheet_name=None)

            valid_sheets = []

            # Load all non-empty sheets from the tokenized Excel file.
            for sheet_name, temp_df in sheets.items():
                if not temp_df.empty:
                    temp = torch.tensor(temp_df.to_numpy(), dtype=torch.float32)
                    temp = temp.unsqueeze(0).unsqueeze(0)
                    valid_sheets.append(temp)

            if valid_sheets:
                for sheets in valid_sheets:
                    # Reorder dimensions so that every three rows correspond to
                    # height, center, and width parameters of one MassLinker token.
                    sheets = sheets.permute(0, 1, 3, 2)

                    for wordcount in range(int(sheets.shape[2] / 3)):
                        ret[-1].append(sheets[0][0][3 * (wordcount):3 * (wordcount + 1)])

                ret[-1] = torch.stack(ret[-1])

        return torch.stack(ret), labels, name, torch.stack(is_positives)

    def __len__(self):
        """
        Return the number of samples in the dataset.
        """
        return len(self.samples)

    def __getitem__(self, idx):
        """
        Return MassLinker token tensors and metadata for selected sample indices.

        Parameters
        ----------
        idx : iterable
            Sample indices used to retrieve data.

        Returns
        -------
        tuple
            Sample tensors, labels, sample names, binary group labels, and
            generated class labels.
        """
        return self.samples[idx], [self.label[i] for i in idx], [self.name[i] for i in idx], self.is_positive[idx], [
            self.classes[i] for i in idx]

    def save_dataset(self, save_path):
        """
        Serialize the current dataset object to disk.

        Parameters
        ----------
        save_path : str
            Output path for the joblib file.
        """
        joblib.dump(self, save_path)

    def gen_classes(self):
        """
        Generate class labels for supervised modeling.

        Samples with `is_positive == 0` are assigned to class 0. Positive samples
        are assigned class IDs according to their label values. This enables
        binary or multiclass modeling depending on the downstream setting.
        """
        classes_list = []
        unique_classes = []

        for i in range(len(self.is_positive)):
            if self.is_positive[i] == 0:
                classes_list.append(0)
            else:
                if self.label[i].item() in unique_classes:
                    classes_list.append(unique_classes.index(self.label[i].item()) + 1)
                else:
                    unique_classes.append(self.label[i].item())
                    classes_list.append(len(unique_classes))

        self.classes = classes_list


def load_data(filename, n_part=5):
    """
    Load a serialized MassLinker dataset and generate cross-validation splits.

    Parameters
    ----------
    filename : str
        Path to a joblib-serialized `ExcelDataset` object.
    n_part : int, optional
        Number of dataset partitions.

    Returns
    -------
    tuple
        Loaded dataset and randomly generated split indices.
    """
    x = joblib.load(filename)
    x.gen_classes()
    split_idx = split_dataset(len(x), n_part)

    return x, split_idx


def split_dataset(n: int, m: int) -> list[list[int]]:
    """
    Randomly split sample indices into multiple partitions.

    Parameters
    ----------
    n : int
        Total number of samples.
    m : int
        Number of partitions.

    Returns
    -------
    list[list[int]]
        A list of index lists, where each sublist corresponds to one partition.
    """
    numbers = list(range(n))
    random.shuffle(numbers)

    base_size = n // m
    remainder = n % m

    result = [[] for _ in range(m)]
    current_index = 0

    for i in range(m):
        current_partition_size = base_size + (1 if i < remainder else 0)
        result[i] = numbers[current_index: current_index + current_partition_size]
        current_index += current_partition_size

    return result


def data_transform(data):
    """
    Flatten MassLinker token tensors into two-dimensional feature matrices.

    This transformation is used by conventional machine-learning models such
    as SVM, random forest, XGBoost, and LightGBM.

    Parameters
    ----------
    data : torch.Tensor or np.ndarray
        MassLinker token tensor.

    Returns
    -------
    torch.Tensor or np.ndarray
        Flattened sample-by-feature matrix.
    """
    return data.reshape(data.shape[0], -1)


def data_rev_transform(data, Metabo_count=5194):
    """
    Restore flattened MassLinker features to token-shaped representation.

    The default MassLinker representation contains 5194 KEGG-associated
    compounds, three RBF parameter types, and 20 RBF components.

    Parameters
    ----------
    data : torch.Tensor or np.ndarray
        Flattened MassLinker feature vector.
    Metabo_count : int, optional
        Number of compound-associated metabolic tokens.

    Returns
    -------
    torch.Tensor or np.ndarray
        Restored token tensor with shape approximately
        `Metabo_count x 3 x 20`.
    """
    return data.reshape(1, Metabo_count, 3, 20)[0]


def gen_feature_names(names=None):
    """
    Generate flattened feature names for MassLinker RBF-derived parameters.

    If `names` is not provided, names are loaded from `names.pth`. Each
    MassLinker token contributes 20 component-level feature names.

    Parameters
    ----------
    names : list, optional
        Raw token or compound names.

    Returns
    -------
    list
        Flattened feature names.
    """
    if names is None:
        names = torch.load('names.pth')

    feature_names = list()

    for i in range(20):
        for j in names:
            temp = j.split("_")
            feature_names.append(temp[1] + '_' + temp[2] + str(i))

    return feature_names


def data_center_rev(data):
    """
    Reverse normalized RBF center coordinates along the retention-time axis.

    This function is used when datasets with different initial polarity or
    chromatographic orientation need to be aligned before concatenation.

    Parameters
    ----------
    data : ExcelDataset
        Dataset whose RBF center parameters will be transformed.

    Returns
    -------
    ExcelDataset
        Dataset with transformed RBF center coordinates.
    """
    data.samples[:, :, 1, :] = 1800 - data.samples[:, :, 1, :]
    return data


def concat_dataset(data_dir, init_polarity_dir):
    """
    Concatenate multiple serialized MassLinker datasets.

    The function reads dataset-level polarity information and applies
    retention-time center reversal when the initial polarity is marked as
    `low`. All datasets are then concatenated into a single dataset object.

    Parameters
    ----------
    data_dir : str
        Directory containing serialized MassLinker datasets.
    init_polarity_dir : str
        Excel file containing dataset names and initial polarity information.

    Returns
    -------
    ExcelDataset
        Concatenated MassLinker dataset.
    """
    init_polarity = pd.read_excel(init_polarity_dir, dtype='string')
    dataset_list = []

    for file in os.listdir(data_dir):
        if file.split('.')[0] in list(init_polarity["dataset"]):

            if (init_polarity["init_polarity"][init_polarity["dataset"] == file.split('.')[0]] == 'low').iloc[0]:
                dataset_list.append(data_center_rev(joblib.load(os.path.join(data_dir, file))))
            else:
                dataset_list.append(joblib.load(os.path.join(data_dir, file)))

    init_dataset = dataset_list[0]

    for i in range(1, len(dataset_list)):
        init_dataset.label += dataset_list[i].label
        init_dataset.name += dataset_list[i].name
        init_dataset.is_positive = torch.concat((init_dataset.is_positive, dataset_list[i].is_positive))
        init_dataset.samples = torch.concat((init_dataset.samples, dataset_list[i].samples))

    init_dataset.gen_classes()

    return init_dataset
